# Generated by Django 4.2.13 on 2024-06-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('age', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=255)),
                ('experience_duration', models.CharField(max_length=100)),
                ('last_employer', models.CharField(max_length=255)),
                ('last_position', models.CharField(max_length=255)),
                ('employment_dates', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('compensation', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
